<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        (function () {
            var type = document.getElementById('banner_type'),
                title = document.getElementById('title');

            function toggleHtmlFields(show) {
                var fields = document.querySelectorAll('.is-html-field, #product_image_path');
                for (var i = 0; i < fields.length; i++) {
                    var row = fields[i].parentNode.parentNode;
                    show ? row.removeAttribute('hidden') : row.setAttribute('hidden', true);
                }
            }

            function copyField(dest) {
                dest.value = this.value;
            }

            if (typeof type !== 'undefined') {
                type.addEventListener('change', function () {
                    toggleHtmlFields(parseInt(this.value))
                }, false);

                toggleHtmlFields(parseInt(type.value));
            }

            title.addEventListener('input', copyField.bind(title, document.getElementById('identifier')));
        })();
    });
</script>
