<?php
/**
 * Unicode Systems
 * @category   Uni
 * @package    Uni_Banner
 * @copyright  Copyright (c) 2010-2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->getSkinUrl('unibanner/css/glider.css') ?>" />
<!--[if IE ]>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('unibanner/css/opacityother.css') ?>" " media="all" />
<![endif]-->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('unibanner/css/noieopacity.css') ?>"  media="all" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('unibanner/js/glider.js') ?>"></script>
<?php
$bannerGroupCode = $this->getBannerGroupCode();
$data = $this->getDataByGroupCode($bannerGroupCode);
$bannerGroupData = $data['group_data'];
$mediaDir = Mage::getBaseDir('media');
$bannerData = $data['banner_data'];
$bannerdest = (($bannerGroupData->getLinkTarget() == 0) ? '_blank' : '_self');
$bannerType = $bannerGroupData->getAnimationType();
$bannerWidth = $bannerGroupData->getBannerWidth();
$bannerHeight = $bannerGroupData->getBannerHeight();

$styleBWH = 'width: ' . $bannerWidth . 'px; height: ' . $bannerHeight . 'px;';
$duration = Mage::getStoreConfig('banner/banner/banner_time_delay');
$autoplay = Mage::getStoreConfig('banner/banner/banner_autoplay');
$durat = $duration / 1000;
$imageWidth = ((int) $bannerWidth - 2);
$imageHeight = ((int) $bannerHeight - 2);
$styleWH = 'width: ' . $imageWidth . 'px; height: ' . $imageHeight . 'px;';
?>
<style type="text/css">
    div#sliderhori{<?php echo $styleBWH; ?>;}
    div.scrollerhori{<?php echo $styleWH; ?>;}
    div.scrollerhori div.sectionhori{<?php echo $styleWH; ?>;}
    div.scrollerhori div.contenthori{<?php echo $styleWH; ?>;}
    div.scrollerhori div.sectionhori img{<?php echo $styleWH; ?>;}
    .bannerlinergliderhori{width:<?php echo ($imageWidth . "px"); ?>;}
</style>
<div id="sliderhori">    
    <div class="scrollerhori">
        <div class="contenthori">
            <?php
            $i = 0;
            foreach ($bannerData as $banner):
                $i++;
                $v = "imgglid" . $i;
                $bannerPath = $banner->getFilename();
                $bannerCon = $banner->getBannerContent();
                $bannerTitle = $banner->getTitle();
                $bannerType = $banner->getBannerType();
                $bannerLink = $banner->getLink();
                if ($bannerType == 0):
                    $bannerImage = '';
                    if ($bannerPath != '' && @file_exists($mediaDir . DS . $bannerPath)):
                        $bannerImage = $this->getResizeImage($bannerPath, $bannerGroupCode, $imageWidth, $imageHeight);
                    endif;
                    $bannerLink = $banner->getLink();
                    if ($bannerImage != '') :
                        ?>
                        <div class="sectionhori" id="sectionhori<?php echo $i; ?>"><a href="<?php echo (($bannerLink) ? $bannerLink : 'javascript:'); ?>" <?php echo (($bannerLink) ? 'target="' . $bannerdest . '"' : ''); ?>><img id="<?php echo $v; ?>" src="<?php echo $bannerImage; ?>" alt="<?php echo $bannerTitle; ?>"/></a></div>
                    <?php endif;
                else: ?>
                    <div class="sectionhori" id="sectionhori<?php echo $i; ?>"><a href="<?php echo (($bannerLink) ? $bannerLink : 'javascript:'); ?>" <?php echo (($bannerLink) ? 'target="' . $bannerdest . '"' : ''); ?> title="<?php echo $bannerTitle; ?>"><?php echo $bannerCon; ?></a></div>
                <?php endif;
            endforeach; ?>
        </div>
        <script type="text/javascript">
            var my_gliderhori = new Glider('sliderhori', {scroller: 'div.scrollerhori', sections: 'div.sectionhori', duration:<?php echo $durat; ?>, autoGlide: <?php echo (($autoplay == 1) ? 'true' : 'false'); ?>, frequency:<?php echo (int) $durat * 2; ?>, initialSection: 'sectionhori1'});
        </script>
    </div>
    <div class="bannerlinergliderhori"></div>
    <div class="slidercontrolhori">
        <a href="javascript:" class="aprev" title="<?php echo $this->__('Previous') ?>" onclick="my_gliderhori.previous();return false;"><?php echo $this->__('Previous') ?></a>
        <a href="javascript:" class="astop" title="<?php echo $this->__('Stop') ?>" onclick="my_gliderhori.stop();return false"><?php echo $this->__('Stop') ?></a>
        <a href="javascript:" class="aplay" title="<?php echo $this->__('Play') ?>" onclick="my_gliderhori.start();return false"><?php echo $this->__('Start') ?></a>
        <a href="javascript:" class="anext" title="<?php echo $this->__('Next') ?>" onclick="my_gliderhori.next();return false"><?php echo $this->__('Next') ?></a>
    </div>
</div>