<?php
/**
 * Created by Macopedia.
 * Developer: Agata Firlejczyk <a.firlejczyk@macopedia.pl>
 */
?>

<?php
    $_banner = $this->getBanner($this->getBannerId());

    $_bannerPath = $_banner->getFilename();
    $_bannerTitle = $_banner->getTitle();
    $_bannerLink = $_banner->getLink();
    $_bannerContent = $_banner->getBannerContent();

    $_extraClass = '';
    if ($_banner->getMobile()) {
        $_extraClass = 'show-for-small-only';
    } else {
        $_extraClass = 'hide-for-small';
    }
?>

<?php if($_banner->getBannerType() == 0) : ?>
    <?php
    $_bannerImage = '';
    if ($_bannerPath != '' && @file_exists($this->getMediaDir() . DS . $_bannerPath)) {
        $_bannerImage = $this->getBannerImg($_bannerPath);
    }
    ?>
    <?php if ($_bannerImage != ''): ?>
        <div class="banner <?php echo $_extraClass ?>">
            <a href="<?php echo ($_bannerLink); ?>"
               title="<?php echo $_bannerTitle; ?>">
                <img src="<?php echo $_bannerImage; ?>" width="100%" height="100%" alt="<?php echo $_bannerTitle; ?>"/></a>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="banner <?php echo $_extraClass ?>">
        <a href="<?php echo $_bannerLink; ?>" title="<?php echo $_bannerTitle; ?>" >
            <?php echo $_bannerContent; ?>
        </a>
    </div>
<?php endif;?>